// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Slutuppgift_Camp_Julia.Data;

namespace Slutuppgift_Camp_Julia.Migrations
{
    [DbContext(typeof(CampContext))]
    [Migration("20220207131327_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Slutuppgift_Camp_Julia.Models.Cabin", b =>
                {
                    b.Property<int>("CabinID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CabinID");

                    b.ToTable("Cabins");
                });

            modelBuilder.Entity("Slutuppgift_Camp_Julia.Models.Camper", b =>
                {
                    b.Property<int>("CamperID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FistName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CamperID");

                    b.ToTable("Campers");
                });

            modelBuilder.Entity("Slutuppgift_Camp_Julia.Models.CamperStay", b =>
                {
                    b.Property<int>("CamperStayID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CabinID")
                        .HasColumnType("int");

                    b.Property<int>("CamperID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2");

                    b.HasKey("CamperStayID");

                    b.HasIndex("CabinID");

                    b.HasIndex("CamperID");

                    b.ToTable("CamperStay");
                });

            modelBuilder.Entity("Slutuppgift_Camp_Julia.Models.Councelor", b =>
                {
                    b.Property<int>("CouncelorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FistName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CouncelorID");

                    b.ToTable("Councelors");
                });

            modelBuilder.Entity("Slutuppgift_Camp_Julia.Models.CouncelorStay", b =>
                {
                    b.Property<int>("CouncelorStayID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CabinID")
                        .HasColumnType("int");

                    b.Property<int>("CouncelorID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2");

                    b.HasKey("CouncelorStayID");

                    b.HasIndex("CabinID");

                    b.HasIndex("CouncelorID");

                    b.ToTable("CouncelorsStay");
                });

            modelBuilder.Entity("Slutuppgift_Camp_Julia.Models.NextOfKin", b =>
                {
                    b.Property<int>("NextOfKinID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FistName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NextOfKinID");

                    b.ToTable("NextOfKin");
                });

            modelBuilder.Entity("Slutuppgift_Camp_Julia.Models.NextOfKinVisit", b =>
                {
                    b.Property<int>("NextOfKinVisitID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CamperID")
                        .HasColumnType("int");

                    b.Property<int>("NextOfKinID")
                        .HasColumnType("int");

                    b.HasKey("NextOfKinVisitID");

                    b.HasIndex("CamperID");

                    b.HasIndex("NextOfKinID");

                    b.ToTable("NextOfKinVisit");
                });

            modelBuilder.Entity("Slutuppgift_Camp_Julia.Models.CamperStay", b =>
                {
                    b.HasOne("Slutuppgift_Camp_Julia.Models.Cabin", null)
                        .WithMany("CamperStay")
                        .HasForeignKey("CabinID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Slutuppgift_Camp_Julia.Models.Camper", null)
                        .WithMany("CamperStay")
                        .HasForeignKey("CamperID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Slutuppgift_Camp_Julia.Models.CouncelorStay", b =>
                {
                    b.HasOne("Slutuppgift_Camp_Julia.Models.Cabin", null)
                        .WithMany("CouncelorStay")
                        .HasForeignKey("CabinID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Slutuppgift_Camp_Julia.Models.Councelor", null)
                        .WithMany("CouncelorStay")
                        .HasForeignKey("CouncelorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Slutuppgift_Camp_Julia.Models.NextOfKinVisit", b =>
                {
                    b.HasOne("Slutuppgift_Camp_Julia.Models.Camper", null)
                        .WithMany("NextOfKinVisit")
                        .HasForeignKey("CamperID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Slutuppgift_Camp_Julia.Models.NextOfKin", null)
                        .WithMany("NextOfKinVisit")
                        .HasForeignKey("NextOfKinID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Slutuppgift_Camp_Julia.Models.Cabin", b =>
                {
                    b.Navigation("CamperStay");

                    b.Navigation("CouncelorStay");
                });

            modelBuilder.Entity("Slutuppgift_Camp_Julia.Models.Camper", b =>
                {
                    b.Navigation("CamperStay");

                    b.Navigation("NextOfKinVisit");
                });

            modelBuilder.Entity("Slutuppgift_Camp_Julia.Models.Councelor", b =>
                {
                    b.Navigation("CouncelorStay");
                });

            modelBuilder.Entity("Slutuppgift_Camp_Julia.Models.NextOfKin", b =>
                {
                    b.Navigation("NextOfKinVisit");
                });
#pragma warning restore 612, 618
        }
    }
}
